# Change these first
owner: jpleasants # Your GitHub organization or username, where this repository lives
repo: plesk12 # The name of this repository
delay: 2000 # 2 seconds

sites:
  - name: guruindiancuisine
    url: https://guruindiancuisine.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Plesk 12
    url: https://plesk12.samitsolutions.com
    port: 8443
    maxResponseTime: 15000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: imcs
    url: https://imcs.sx
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: samanalyticsolutions
    url: https://samanalyticsolutions.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: asliceofthecloud
    url: https://asliceofthecloud.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: bikanerelectrical
    url: https://bikanerelectrical.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Cary Endoscopy Center
    url: https://caryendoscopycenter.com
    maxResponseTime: 15000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Cary Internal Medicine
    url: https://caryinternalmedicine.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Center For Digestive Diseases
    url: centerfordigestivediseases.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: directed-vr
    url: https://directed-vr.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: docnc
    url: https://docnc.org
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: hcilcode
    url: https://hcilcode.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: jalwaindianbistro
    url: https://jalwaindianbistro.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: prdbi
    url: https://prdbi.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: prodigybiotech
    url: https://prodigybiotech.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: temoacloud
    url: https://temoacloud.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: rahul-priyadarshi
    url: https://rahul-priyadarshi.net
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: tasteoftandoor
    url: https://tasteoftandoor.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: laysciences
    url: https://laysciences.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: Patagonia Health
    url: https://patagoniahealth.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: thalirtp
    url: https://thalirtp.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: veearcapital
    url: https://veearcapital.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: kingstandoorandbar
    url: https://kingstandoorandbar.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: zaykaraleigh
    url: https://zaykaraleigh.com
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 201
      - 403
  - name: oceanbayindiancuisine
    url: https://oceanbayindiancuisine.com
    maxResponseTime: 15000
    expectedStatusCodes:
      - 200
      - 201
      - 403
               
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /plesk12
  logoUrl: https://samitpublic.blob.core.windows.net/download/sam-it-dots(1).png
  name: SAM IT Solutions
  theme: night
  introTitle: "**Status** page highlighting active incidents, current status of endpoints, and historical data."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: ""

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
